### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ghost** [RK0731/Deep-reinforcement-learning-for-dynamic-scheduling-of-a-flexible-job-shop#1]
抱歉打扰到你，请问这个routing_models" and "sequencing_models里面的参数具体是怎么用的，routing agent (RA) and sequencing agent (SA)在文件中我没有找到这两个代理

**Comment by RK0731** [comment]
Hi LFgoodday,

You may find the trained parameters in "routing_models" and  "sequencing_models" folders.

To build a RA and SA agent, you need to create an instance of routing/sequencing brain in the experiment, then import the trained parameters. 

For example, in **main_experiment_R.py**, STEP 5:

        # specify the architecture of DRL
        if 'arch' and 'global_reward' in kwargs:
            arch = kwargs['arch'] + "=True"
            global_reward = 'global_reward={}'.format(kwargs['global_reward'])
            order = "self.routing_brain = validation_R.DRL_routing(self.env, self.job_creator, self.wc_list, {},{})".format(arch,global_reward)
            exec(order)

Please also take a look at the updated README file for more details.
